# Álgebra Lineal 2024 1er. cuatrimestre - Laboratorio 4

Esta notebook elaborada por la cátedra es para trabajar diagonalización.

In [1]:
# Cargamos NumPy.
import numpy as np
# Cargamos Sympy
#from sympy import Matrix
#from sympy.matrices import zeros
#from sympy import shape
from sympy import *

## 0. Matrices por bloques

Vamos a mostrar cómo ingresar matrices por bloques en Sympy.



Supongamos que queremos armar la matriz siguiente:

$$ A = \begin{pmatrix} 
-1 & 0 & 0 & 0 & 0 & 0  \\
0 & 1 & 1 & 0 & 0 & 0  \\
0 & 1 & 1 & 0 & 0 & 0  \\
0 & 0 & 0 & 2 & 1 & -2  \\
0 & 0 & 0 & 1 & 3 & -1  \\
0 & 0 & 0 & 4 & 5 & 0  
\end{pmatrix} $$

Esta matriz tiene 3 bloques diagonales: uno $1\times 1$ , uno $2\times 2$ y uno $3\times3$.

In [2]:
A = diag(-1, ones(2, 2), Matrix([[5, 7, 5],[2,2,4],[2,3,1]]))
A

Matrix([
[-1, 0, 0, 0, 0, 0],
[ 0, 1, 1, 0, 0, 0],
[ 0, 1, 1, 0, 0, 0],
[ 0, 0, 0, 5, 7, 5],
[ 0, 0, 0, 2, 2, 4],
[ 0, 0, 0, 2, 3, 1]])

Armemos ahora la matriz $$\begin{pmatrix} 1 & 0 & 1 & 1 \\ 0 & 1 & 1 & 1 \\ 0 & 2 & 4 & 5 \end{pmatrix}.$$

Esta matriz tiene un bloque identidad $2\times 2$ seguido de un bloque de unos $2\times 2$ y abajo una fila $1\times 4$.

In [3]:
B = Matrix([[eye(2),ones(2)],[0, 2, 4, 5]])
B

Matrix([
[1, 0, 1, 1],
[0, 1, 1, 1],
[0, 2, 4, 5]])

En general se pueden construir matrices de estas formas, basta con probar.

## 1. Autovalores y autovectores


Dada una matriz $A\in F^{n\times n}$ podemos calcular sus autovalores y autovectores asociados, chequear si es diagonalizable y de serlo, encontrar la base donde es diagonal así como la descomposición de $F^n$ en autoespacios.

In [4]:
M = Matrix([[3, -2,  4, -2], [5,  3, -3, -2], [5, -2,  2, -2], [5, -2, -3,  3]])
M

Matrix([
[3, -2,  4, -2],
[5,  3, -3, -2],
[5, -2,  2, -2],
[5, -2, -3,  3]])

In [5]:
M.eigenvals()

{3: 1, -2: 1, 5: 2}

Este diccionario lo interpretamos así:
3 es un autovalor de M de multiplicidad 1
-2 es un autovalor de M de multiplicidad 1
5 es un autovalor de M de multiplicidad 2

Aquí multiplicidad significa multiplicidad como raíz del polinomio característico. Podemos también calcularlo:

In [6]:
M.charpoly()

PurePoly(lambda**4 - 11*lambda**3 + 29*lambda**2 + 35*lambda - 150, lambda, domain='ZZ')

Para factorizarlo basta pedirle las raíces:

In [7]:
M.charpoly().all_roots()

[-2, 3, 5, 5]

Calculemos ahora los autovectores. Sympy te da una base del autoespacio asociado:

In [8]:
M.eigenvects()

[(-2,
  1,
  [Matrix([
   [0],
   [1],
   [1],
   [1]])]),
 (3,
  1,
  [Matrix([
   [1],
   [1],
   [1],
   [1]])]),
 (5,
  2,
  [Matrix([
   [1],
   [1],
   [1],
   [0]]),
   Matrix([
   [ 0],
   [-1],
   [ 0],
   [ 1]])])]

Cada salida es una terna donde figuran autovalor, su multiplicidad y una base del autoespacio.

Vemos que el autoespacio asociado al autovalor -2 tiene dimensión 1 y está generado por (0,1,1,1).

In [9]:
v1 = Matrix([[0],[1],[1],[1]])

In [10]:
M*v1

Matrix([
[ 0],
[-2],
[-2],
[-2]])

In [11]:
M*v1 == -2*v1

True

El autoespacio $E_{-2}$ es el espacio nulo de $M-(-2)I$:

In [12]:
M_autov1 = M + 2*eye(4)
M_autov1

Matrix([
[5, -2,  4, -2],
[5,  5, -3, -2],
[5, -2,  4, -2],
[5, -2, -3,  5]])

In [13]:
M_autov1.nullspace()

[Matrix([
 [0],
 [1],
 [1],
 [1]])]

Es decir, el autoespacio correspondiente al primer autovalor está, efectivamente, generado por v1.

De la misma forma, vemos que el autoespacio asociado al autovalor 5 tiene dimensión 2 y está generado por (1,1,1,0) y (0,-1,0,1).

In [14]:
v3 = Matrix([[1],[1],[1],[0]])
v4 = Matrix([[0],[-1],[0],[ 1]])

In [15]:
M*v3 == 5*v3, M*v4 == 5*v4, M*v1 == 5*v1

(True, True, False)

In [16]:
M_autov3 = M - 5*eye(4)
M_autov3

Matrix([
[-2, -2,  4, -2],
[ 5, -2, -3, -2],
[ 5, -2, -3, -2],
[ 5, -2, -3, -2]])

In [17]:
M_autov3.nullspace()

[Matrix([
 [1],
 [1],
 [1],
 [0]]),
 Matrix([
 [ 0],
 [-1],
 [ 0],
 [ 1]])]

Vemos que $M$ diagonaliza. Su forma diagonal sería entonces $D = diag(-2,3,5,5)$ y una matriz de cambio de base está dada por $P=([v_1],[v_2],[v_3],[v_4])$ (qué sería $v_2$?).

In [18]:
P,D = M.diagonalize()

In [19]:
D

Matrix([
[-2, 0, 0, 0],
[ 0, 3, 0, 0],
[ 0, 0, 5, 0],
[ 0, 0, 0, 5]])

In [20]:
P

Matrix([
[0, 1, 1,  0],
[1, 1, 1, -1],
[1, 1, 1,  0],
[1, 1, 0,  1]])

In [22]:
M.is_diagonalizable()

True

EJERCICIO: Corroborar los resultados del práctico.

## 2 Polinomio minimal


In [23]:
I = eye(4)

In [32]:
e1 = Matrix([[1],[0],[0],[0]])

In [34]:
e1,M*e1,M**2*e1

(Matrix([
 [1],
 [0],
 [0],
 [0]]),
 Matrix([
 [3],
 [5],
 [5],
 [5]]),
 Matrix([
 [9],
 [5],
 [5],
 [5]]))

In [54]:
A1 = Matrix([[e1.transpose()],[(M*e1).transpose()],[(M**2*e1).transpose()]]).transpose()

In [58]:
A1_fer, A1_pivots = A1.rref()
A1_fer, A1_pivots

(Matrix([
 [1, 0, 6],
 [0, 1, 1],
 [0, 0, 0],
 [0, 0, 0]]),
 (0, 1))

Es decir, el conjunto $\{e_1,Me_1,M^2e_1\}$, y $\{e_1,Me_1\}$ es li. Entonces podemos calcular el polinomio minimal $m_{e_1}$ resolviendo el sistema $a_0 e_1 + a_1 Me_1 + M^2e_1 = 0$.

De esta solución vemos que el sistema homogéneo $A1(a,b,c)^t=\overline{0}^t$ es equivalente a $a + 6c =0,b+c=0$. Poniendo $c=1$ para que sea mónico el polinomio, sigue que $m_{e_1} = -6 -x -x^2$.

In [77]:
x= symbols('x')
#init_printing(use_unicode=False, wrap_line=False)

In [85]:
m1 = -6 - x+ x**2

In [86]:
m1 = m1.as_poly()

In [87]:
m1.all_roots()

Así, $m_{e_1}(x)=(x+2)(x-3)$.

Análogamente,

$m_{e_2}(x)=(x-3)(x-5)$

$m_{e_3}(x)=(x+2)(x-3)(x-5)$

$m_{e_4}(x)=(x-3)(x-5)$

De donde $m_M(x)=mcm\{m_{e_1},m_{e_2},m_{e_3},m_{e_4}\} = (x+2)(x-3)(x-5)$.

Observemos que $m_M|chi_M$.

Además, todas las raíces de $m_M$ son simples.


In [88]:
e2 = Matrix([[0],[1],[0],[0]])

In [92]:
A2 = Matrix([[e2.transpose()],[(M*e2).transpose()],[(M**2*e2).transpose()]]).transpose()
A2_fer, A2_pivots = A2.rref()
A2_fer, A2_pivots

 [1  0  -15]         
 [         ]         
 [0  1   8 ]         
([         ], (0, 1))
 [0  0   0 ]         
 [         ]         
 [0  0   0 ]         

a - 15c = 0 y b+8c =0

In [101]:
m2 = 15 - 8*x+ x**2
m2 = m2.as_poly()
m2.all_roots()

In [102]:
e3 = Matrix([[0],[0],[1],[0]])

In [97]:
A3 = Matrix([[e3.transpose()],[(M*e3).transpose()],[(M**2*e3).transpose()]]).transpose()
A3_fer, A3_pivots = A3.rref()
A3_fer, A3_pivots

 [1  0  0]            
 [       ]            
 [0  1  0]            
([       ], (0, 1, 2))
 [0  0  1]            
 [       ]            
 [0  0  0]            

In [100]:
A3 = Matrix([[e3.transpose()],[(M*e3).transpose()],[(M**2*e3).transpose()],[(M**3*e3).transpose()]]).transpose()
A3_fer, A3_pivots = A3.rref()
A3_fer, A3_pivots

 [1  0  0  -30]            
 [            ]            
 [0  1  0   1 ]            
([            ], (0, 1, 2))
 [0  0  1   6 ]            
 [            ]            
 [0  0  0   0 ]            

a -30 d =0, b+d = 0, c+6d=0

In [103]:
m3 = 30 - x - 6* x**2 + x**3
m3 = m3.as_poly()
m3.all_roots()

In [104]:
e4 = Matrix([[0],[0],[0],[1]])

In [105]:
A4 = Matrix([[e4.transpose()],[(M*e4).transpose()],[(M**2*e4).transpose()]]).transpose()
A4_fer, A4_pivots = A4.rref()
A4_fer, A4_pivots

 [1  0  -15]         
 [         ]         
 [0  1   8 ]         
([         ], (0, 1))
 [0  0   0 ]         
 [         ]         
 [0  0   0 ]         

a-15c =0 , b+8c=0

In [106]:
m4 = 15 - 8*x + x**2
m4 = m4.as_poly()
m4.all_roots()

EJERCICIO: Corroborar los resultados del práctico.

---
Estas notebooks fueron confeccionadas pa ra la asignatura Álgebra Lineal correspondiente al primer cuatrimestre de segundo año de la Licenciatura en Cs. de la Computación y al redictado para la Licenciatura en Matemática y el Profesorado en Matemática de la Escuela de Cs. Exactas y Naturales de la Facultad de Cs. Exactas, Ingeniería y Agrimensura. La docente responsable es Isolda E. Cardoso (isolda@fceia.unr.edu.ar)

En caso de reproducirlas, se solicita citar la fuente.